/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CourseRouteImport } from './routes/course'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicIdRouteImport } from './routes/topic.$id'
import { Route as ConceptIdRouteImport } from './routes/concept.$id'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdRoute = TopicIdRouteImport.update({
  id: '/topic/$id',
  path: '/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptIdRoute = ConceptIdRouteImport.update({
  id: '/concept/$id',
  path: '/concept/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/history': typeof HistoryRoute
  '/quiz': typeof QuizRoute
  '/concept/$id': typeof ConceptIdRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/history': typeof HistoryRoute
  '/quiz': typeof QuizRoute
  '/concept/$id': typeof ConceptIdRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/history': typeof HistoryRoute
  '/quiz': typeof QuizRoute
  '/concept/$id': typeof ConceptIdRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course'
    | '/history'
    | '/quiz'
    | '/concept/$id'
    | '/topic/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course' | '/history' | '/quiz' | '/concept/$id' | '/topic/$id'
  id:
    | '__root__'
    | '/'
    | '/course'
    | '/history'
    | '/quiz'
    | '/concept/$id'
    | '/topic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRoute: typeof CourseRoute
  HistoryRoute: typeof HistoryRoute
  QuizRoute: typeof QuizRoute
  ConceptIdRoute: typeof ConceptIdRoute
  TopicIdRoute: typeof TopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id': {
      id: '/topic/$id'
      path: '/topic/$id'
      fullPath: '/topic/$id'
      preLoaderRoute: typeof TopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$id': {
      id: '/concept/$id'
      path: '/concept/$id'
      fullPath: '/concept/$id'
      preLoaderRoute: typeof ConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRoute: CourseRoute,
  HistoryRoute: HistoryRoute,
  QuizRoute: QuizRoute,
  ConceptIdRoute: ConceptIdRoute,
  TopicIdRoute: TopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
